spring.application.name=user-service
# activate the console
spring.h2.console.enabled = true
# give an url to the console
spring.h2.console.path = /h2-console
# indicate to Spring Boot which is the DB's url
spring.datasource.url = jdbc:h2:mem:userdb
# port for the user-service
server.port=8081