spring.application.name=user-service
# activate the console
spring.h2.console.enabled = true
# give an url to the console
spring.h2.console.path = /h2-console
# indicate to Spring Boot which is the DB's url
spring.datasource.url = jdbc:h2:mem:userdb
# port for the user-service
server.port=8081

eureka.client.service-url.defaultZone = http://localhost:8761/eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# localhost
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# expiration we can provide any value
jwt.expiration = ${EXPIRATION_TIME}
# environment variable: Base64 format and minimum length 32 bytes
jwt.secret = ${SECRET_KEY}

jwt.verifyUserKey= ${VERIFY_USER_KEY}